// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace SlateDB.Interop
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "slatedb_csharp_ffi";





        [DllImport(__DllName, EntryPoint = "slatedb_last_error_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* slatedb_last_error_message();

        [DllImport(__DllName, EntryPoint = "slatedb_options_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SlateDbOptions* slatedb_options_new();

        [DllImport(__DllName, EntryPoint = "slatedb_options_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_options_free(SlateDbOptions* opts);

        [DllImport(__DllName, EntryPoint = "slatedb_options_set_block_size", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_options_set_block_size(SlateDbOptions* opts, uint block_size);

        [DllImport(__DllName, EntryPoint = "slatedb_options_set_cache_capacity", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_options_set_cache_capacity(SlateDbOptions* opts, ulong cache_capacity_bytes);

        [DllImport(__DllName, EntryPoint = "slatedb_options_set_enable_compression", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_options_set_enable_compression(SlateDbOptions* opts, [MarshalAs(UnmanagedType.U1)] bool enable);

        [DllImport(__DllName, EntryPoint = "slatedb_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SlateDbStatus slatedb_open(byte* path, SlateDbOptions* opts, ulong* out_handle);

        [DllImport(__DllName, EntryPoint = "slatedb_put", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SlateDbStatus slatedb_put(ulong handle, byte* key, int key_len, byte* value, int value_len);

        [DllImport(__DllName, EntryPoint = "slatedb_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SlateDbStatus slatedb_get(ulong handle, byte* key, int key_len, byte** out_value, int* out_len);

        [DllImport(__DllName, EntryPoint = "slatedb_free_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_free_value(byte* ptr, int len);

        [DllImport(__DllName, EntryPoint = "slatedb_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SlateDbStatus slatedb_close(ulong handle);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SlateDbOptions
    {
        public uint block_size;
        public ulong cache_capacity_bytes;
        [MarshalAs(UnmanagedType.U1)] public bool enable_compression;
    }


    internal enum SlateDbStatus : uint
    {
        Ok = 0,
        NotFound = 1,
        Error = 2,
    }


}
