// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace SlateDb.Interop
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "slatedb_csharp_ffi";





        /// <summary>
        ///  Initialize logging for SlateDB Go bindings
        ///  This should be called once before using any other SlateDB functions
        ///
        ///  # Safety
        ///
        ///  - `level` must be a valid C string pointer or null for default level
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_init_logging", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_init_logging(byte* level);

        /// <summary>
        ///  # Safety
        ///
        ///  - `batch_out` must be a valid pointer to a location where a batch pointer can be stored
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_write_batch_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_write_batch_new(CSdbWriteBatch** batch_out);

        /// <summary>
        ///  # Safety
        ///
        ///  - `batch` must be a valid pointer to a WriteBatch
        ///  - `key` must point to valid memory of at least `key_len` bytes
        ///  - `value` must point to valid memory of at least `value_len` bytes
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_write_batch_put", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_write_batch_put(CSdbWriteBatch* batch, byte* key, nuint key_len, byte* value, nuint value_len);

        /// <summary>
        ///  # Safety
        ///
        ///  - `batch` must be a valid pointer to a WriteBatch
        ///  - `key` must point to valid memory of at least `key_len` bytes  
        ///  - `value` must point to valid memory of at least `value_len` bytes
        ///  - `options` must be a valid pointer to CSdbPutOptions or null
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_write_batch_put_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_write_batch_put_with_options(CSdbWriteBatch* batch, byte* key, nuint key_len, byte* value, nuint value_len, CSdbPutOptions* options);

        /// <summary>
        ///  # Safety
        ///
        ///  - `batch` must be a valid pointer to a WriteBatch
        ///  - `key` must point to valid memory of at least `key_len` bytes
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_write_batch_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_write_batch_delete(CSdbWriteBatch* batch, byte* key, nuint key_len);

        /// <summary>
        ///  # Safety
        ///
        ///  - `handle` must contain a valid database handle pointer
        ///  - `batch` must be a valid pointer to a WriteBatch
        ///  - `options` must be a valid pointer to CSdbWriteOptions or null
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_write_batch_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_write_batch_write(CSdbHandle handle, CSdbWriteBatch* batch, CSdbWriteOptions* options);

        /// <summary>
        ///  # Safety
        ///
        ///  - `batch` must be a valid pointer to a WriteBatch that was previously allocated
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_write_batch_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_write_batch_close(CSdbWriteBatch* batch);

        /// <summary>
        ///  Create default Settings and return as JSON string
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_settings_default", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* slatedb_settings_default();

        /// <summary>
        ///  Load Settings from file and return as JSON string
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_settings_from_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* slatedb_settings_from_file(byte* path);

        /// <summary>
        ///  Load Settings from environment variables and return as JSON string
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_settings_from_env", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* slatedb_settings_from_env(byte* prefix);

        /// <summary>
        ///  Load Settings using auto-detection and return as JSON string
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_settings_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* slatedb_settings_load();

        [DllImport(__DllName, EntryPoint = "slatedb_reader_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbReaderHandleResult slatedb_reader_open(byte* path, byte* url, byte* env_file, byte* checkpoint_id, CSdbReaderOptions* reader_options);

        /// <summary>
        ///  # Safety
        ///
        ///  - `handle` must contain a valid reader handle pointer
        ///  - `key` must point to valid memory of at least `key_len` bytes
        ///  - `read_options` must be a valid pointer to CSdbReadOptions or null
        ///  - `value_out` must be a valid pointer to a location where a value can be stored
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_reader_get_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_reader_get_with_options(CSdbReaderHandle handle, byte* key, nuint key_len, CSdbReadOptions* read_options, CSdbValue* value_out);

        /// <summary>
        ///  # Safety
        ///
        ///  - `handle` must contain a valid reader handle pointer
        ///  - `start_key` must point to valid memory of at least `start_key_len` bytes (if not null)
        ///  - `end_key` must point to valid memory of at least `end_key_len` bytes (if not null)
        ///  - `scan_options` must be a valid pointer to CSdbScanOptions or null
        ///  - `iterator_ptr` must be a valid pointer to a location where an iterator pointer can be stored
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_reader_scan_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_reader_scan_with_options(CSdbReaderHandle handle, byte* start_key, nuint start_key_len, byte* end_key, nuint end_key_len, CSdbScanOptions* scan_options, CSdbIterator** iterator_ptr);

        /// <summary>
        ///  # Safety
        ///
        ///  - `handle` must contain a valid reader handle pointer
        ///  - `prefix` must point to valid memory of at least `prefix_len` bytes (unless prefix_len is 0)
        ///  - `scan_options` must be a valid pointer to CSdbScanOptions or null
        ///  - `iterator_ptr` must be a valid pointer to a location where an iterator pointer can be stored
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_reader_scan_prefix_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_reader_scan_prefix_with_options(CSdbReaderHandle handle, byte* prefix, nuint prefix_len, CSdbScanOptions* scan_options, CSdbIterator** iterator_ptr);

        [DllImport(__DllName, EntryPoint = "slatedb_reader_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_reader_close(CSdbReaderHandle handle);

        [DllImport(__DllName, EntryPoint = "slatedb_reader_open_with_object_builder", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbReaderHandleResult slatedb_reader_open_with_object_builder(byte* path, ObjectStoreBuilder* object_store_builder, byte* checkpoint_id, CSdbReaderOptions* reader_options);

        [DllImport(__DllName, EntryPoint = "slatedb_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbHandleResult slatedb_open(byte* path, byte* url, byte* env_file);

        /// <summary>
        ///  # Safety
        ///
        ///  - `handle` must contain a valid database handle pointer
        ///  - `key` must point to valid memory of at least `key_len` bytes
        ///  - `value` must point to valid memory of at least `value_len` bytes
        ///  - `put_options` must be a valid pointer to CSdbPutOptions or null
        ///  - `write_options` must be a valid pointer to CSdbWriteOptions or null
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_put_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_put_with_options(CSdbHandle handle, byte* key, nuint key_len, byte* value, nuint value_len, CSdbPutOptions* put_options, CSdbWriteOptions* write_options);

        /// <summary>
        ///  # Safety
        ///
        ///  - `handle` must contain a valid database handle pointer
        ///  - `key` must point to valid memory of at least `key_len` bytes
        ///  - `write_options` must be a valid pointer to CSdbWriteOptions or null
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_delete_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_delete_with_options(CSdbHandle handle, byte* key, nuint key_len, CSdbWriteOptions* write_options);

        /// <summary>
        ///  # Safety
        ///
        ///  - `handle` must contain a valid database handle pointer
        ///  - `key` must point to valid memory of at least `key_len` bytes
        ///  - `read_options` must be a valid pointer to CSdbReadOptions or null
        ///  - `value_out` must be a valid pointer to a location where a value can be stored
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_get_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_get_with_options(CSdbHandle handle, byte* key, nuint key_len, CSdbReadOptions* read_options, CSdbValue* value_out);

        [DllImport(__DllName, EntryPoint = "slatedb_flush", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_flush(CSdbHandle handle);

        [DllImport(__DllName, EntryPoint = "slatedb_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_close(CSdbHandle handle);

        /// <summary>
        ///  # Safety
        ///
        ///  - `handle` must contain a valid database handle pointer
        ///  - `start_key` must point to valid memory of at least `start_key_len` bytes (if not null)
        ///  - `end_key` must point to valid memory of at least `end_key_len` bytes (if not null)
        ///  - `scan_options` must be a valid pointer to CSdbScanOptions or null
        ///  - `iterator_ptr` must be a valid pointer to a location where an iterator pointer can be stored
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_scan_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_scan_with_options(CSdbHandle handle, byte* start_key, nuint start_key_len, byte* end_key, nuint end_key_len, CSdbScanOptions* scan_options, CSdbIterator** iterator_ptr);

        /// <summary>
        ///  # Safety
        ///
        ///  - `handle` must contain a valid database handle pointer
        ///  - `prefix` must point to valid memory of at least `prefix_len` bytes (unless prefix_len is 0)
        ///  - `scan_options` must be a valid pointer to CSdbScanOptions or null
        ///  - `iterator_ptr` must be a valid pointer to a location where an iterator pointer can be stored
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_scan_prefix_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_scan_prefix_with_options(CSdbHandle handle, byte* prefix, nuint prefix_len, CSdbScanOptions* scan_options, CSdbIterator** iterator_ptr);

        /// <summary>
        ///  # Safety
        ///
        ///  - `handle` must contain a valid database handle pointer
        ///  - `value_out` must be a valid pointer to a location where a value can be stored
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_metrics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_metrics(CSdbHandle handle, CSdbValue* value_out);

        /// <summary>
        ///  Create a new DbBuilder
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_builder_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern DbBuilder* slatedb_builder_new(byte* path, byte* url, byte* env_file);

        /// <summary>
        ///  Set settings on DbBuilder from JSON
        ///
        ///  # Safety
        ///
        ///  - `builder` must be a valid pointer to a DbBuilder
        ///  - `settings_json` must be a valid C string pointer
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_builder_with_settings", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool slatedb_builder_with_settings(DbBuilder* builder, byte* settings_json);

        /// <summary>
        ///  Set SST block size on DbBuilder
        ///
        ///  # Safety
        ///
        ///  - `builder` must be a valid pointer to a DbBuilder
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_builder_with_sst_block_size", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool slatedb_builder_with_sst_block_size(DbBuilder* builder, byte size);

        /// <summary>
        ///  Build the database from DbBuilder
        ///
        ///  # Safety
        ///
        ///  - `builder` must be a valid pointer to a DbBuilder that was previously allocated
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_builder_build", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbHandle slatedb_builder_build(DbBuilder* builder);

        /// <summary>
        ///  Free DbBuilder
        ///
        ///  # Safety
        ///
        ///  - `builder` must be a valid pointer to a DbBuilder that was previously allocated
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_builder_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_builder_free(DbBuilder* builder);

        [DllImport(__DllName, EntryPoint = "slatedb_open_with_object_builder", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbHandleResult slatedb_open_with_object_builder(byte* path, ObjectStoreBuilder* object_store_builder);

        /// <summary>
        ///  Create a new DbBuilder with custom ObjectStoreBuilder
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_builder_new_with_object_builder", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern DbBuilder* slatedb_builder_new_with_object_builder(byte* path, ObjectStoreBuilder* object_store_builder);

        /// <summary>
        ///  # Safety
        ///
        ///  - `iter` must be a valid pointer to a CSdbIterator
        ///  - `kv_out` must be a valid pointer to a location where a key-value pair can be stored
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_iterator_next", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_iterator_next(CSdbIterator* iter, CSdbKeyValue* kv_out);

        /// <summary>
        ///  # Safety
        ///
        ///  - `iter` must be a valid pointer to a CSdbIterator
        ///  - `key` must point to valid memory of at least `key_len` bytes
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_iterator_seek", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_iterator_seek(CSdbIterator* iter, byte* key, nuint key_len);

        /// <summary>
        ///  # Safety
        ///
        ///  - `iter` must be a valid pointer to a CSdbIterator that was previously allocated
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_iterator_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_iterator_close(CSdbIterator* iter);

        /// <summary>
        ///  # Safety
        ///
        ///  - `iter` must be a valid pointer to a CSdbIterator
        ///  - `key` must point to valid memory of at least `key_len` bytes
        /// </summary>
        [DllImport(__DllName, EntryPoint = "slatedb_iterator_seek_from_beginning", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CSdbResult slatedb_iterator_seek_from_beginning(CSdbIterator* iter);

        [DllImport(__DllName, EntryPoint = "slatedb_free_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_free_result(CSdbResult result);

        [DllImport(__DllName, EntryPoint = "slatedb_free_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_free_value(CSdbValue value);

        [DllImport(__DllName, EntryPoint = "slatedb_free_scan_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_free_scan_result(CSdbScanResult result);

        [DllImport(__DllName, EntryPoint = "slatedb_object_store_builder_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ObjectStoreBuilder* slatedb_object_store_builder_new(ObjectStoreType _type, ObjectStoreConfig* config_map);

        [DllImport(__DllName, EntryPoint = "slatedb_object_store_builder_config_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ObjectStoreConfig* slatedb_object_store_builder_config_new();

        [DllImport(__DllName, EntryPoint = "slatedb_object_store_builder_config_set", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_object_store_builder_config_set(ObjectStoreConfig* config, byte* key, byte* value);

        [DllImport(__DllName, EntryPoint = "slatedb_object_store_builder_config_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_object_store_builder_config_delete(ObjectStoreConfig* config, byte* key);

        [DllImport(__DllName, EntryPoint = "slatedb_object_store_builder_config_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ObjectStoreConfigArray slatedb_object_store_builder_config_get(ObjectStoreConfig* config);

        [DllImport(__DllName, EntryPoint = "slatedb_object_store_builder_config_get_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_object_store_builder_config_get_free(ObjectStoreConfigArray arr);

        [DllImport(__DllName, EntryPoint = "slatedb_object_store_builder_config_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void slatedb_object_store_builder_config_free(ObjectStoreConfig* config);


    }

    /// <summary>
    ///  Internal struct that owns a Tokio runtime and a SlateDB DbReader instance.
    ///  Similar to SlateDbFFI but for read-only operations.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SlateDbReaderFFI
    {
    }

    /// <summary>
    ///  Type-safe wrapper around a pointer to DbReaderFFI.
    ///  This provides better type safety than raw pointers.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbReaderHandle
    {
        public SlateDbReaderFFI* Item1;
    }

    /// <summary>
    ///  DbReader options for FFI
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbReaderOptions
    {
        /// <summary>
        ///  How often to poll for manifest updates (in milliseconds)
        /// </summary>
        public ulong manifest_poll_interval_ms;
        /// <summary>
        ///  How long checkpoints should live (in milliseconds)
        /// </summary>
        public ulong checkpoint_lifetime_ms;
        /// <summary>
        ///  Max size of in-memory table for WAL buffering
        /// </summary>
        public ulong max_memtable_bytes;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbResult
    {
        public CSdbError error;
        public byte* message;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbHandleResult
    {
        public CSdbHandle handle;
        public CSdbResult result;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbReaderHandleResult
    {
        public CSdbReaderHandle handle;
        public CSdbResult result;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ObjectStoreBuilder
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ObjectStoreConfig
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ObjectStoreConfigItem
    {
        public byte* key;
        public byte* value;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ObjectStoreConfigArray
    {
        public ObjectStoreConfigItem* data;
        public nuint len;
    }

    /// <summary>
    ///  Internal struct that owns a Tokio runtime and a SlateDB instance.
    ///  This eliminates the need for a global handle map and shared runtime.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SlateDbFFI
    {
    }

    /// <summary>
    ///  Type-safe wrapper around a pointer to SlateDbFFI.
    ///  This provides better type safety than raw u64 handles.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbHandle
    {
        public SlateDbFFI* Item1;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbValue
    {
        public byte* data;
        public nuint len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbKeyValue
    {
        public CSdbValue key;
        public CSdbValue value;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbScanResult
    {
        public CSdbKeyValue* items;
        public nuint count;
        [MarshalAs(UnmanagedType.U1)] public bool has_more;
        public CSdbValue next_key;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbWriteOptions
    {
        [MarshalAs(UnmanagedType.U1)] public bool await_durable;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbPutOptions
    {
        /// <summary>
        ///  TTL type: 0=Default, 1=NoExpiry, 2=ExpireAfter
        /// </summary>
        public uint ttl_type;
        /// <summary>
        ///  TTL value in milliseconds (only used when ttl_type=2)
        /// </summary>
        public ulong ttl_value;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbReadOptions
    {
        /// <summary>
        ///  Durability filter: 0=Memory, 1=Remote
        /// </summary>
        public uint durability_filter;
        /// <summary>
        ///  Whether to include dirty/uncommitted data
        /// </summary>
        [MarshalAs(UnmanagedType.U1)] public bool dirty;
        /// <summary>
        ///  Whether to cache fetched blocks
        /// </summary>
        [MarshalAs(UnmanagedType.U1)] public bool cache_blocks;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbScanOptions
    {
        public int durability_filter;
        [MarshalAs(UnmanagedType.U1)] public bool dirty;
        public ulong read_ahead_bytes;
        [MarshalAs(UnmanagedType.U1)] public bool cache_blocks;
        public ulong max_fetch_tasks;
    }

    /// <summary>
    ///  Contains the iterator and a reference to the owner to ensure proper lifetime management
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbIterator
    {
    }

    /// <summary>
    ///  Internal struct for managing WriteBatch operations in FFI
    ///  Contains the WriteBatch that can be moved out when writing to the database
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CSdbWriteBatch
    {
    }


    internal enum CSdbError : uint
    {
        Success = 0,
        InvalidArgument = 1,
        NotFound = 2,
        AlreadyExists = 3,
        IOError = 4,
        InternalError = 5,
        NullPointer = 6,
        InvalidHandle = 7,
        InvalidProvider = 8,
    }

    internal enum ObjectStoreType : uint
    {
        Azure,
        Local,
        InMemory,
        S3,
        GCS,
    }


}
