name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: ./generate-binding.sh 0.10.1
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Run dotnet tests
        shell: bash
        run: |
          cd src/SlateDbUnitTests
          dotnet test --verbosity normal