name: Integration Tests

on:
  push:
    branches: [ integration ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            targets: macOS + linux + windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"
      
      - uses: dtolnay/rust-toolchain@nightly
      - uses: goto-bus-stop/setup-zig@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Make script executable
        run: |
          chmod +x ./generate-binding.sh && chmod +x ./get-slatedb-c-bindings.sh

      - run: cargo install cargo-zigbuild

      - name: Generate bindings
        shell: bash
        run: ./generate-binding.sh 0.10.1 all

      - name: Run dotnet tests
        shell: bash
        run: |
          cd src/SlateDbUnitTests
          dotnet test --verbosity normal

      - name: Upload native libs artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-libs-${{ matrix.os }}
          path: src/SlateDb/runtimes
          retention-days: 1